#ifndef tokenlexico
#define tokenlexico

enum TokenTipo {
    TOKEN_KEYW_PROGRAMA,
    TOKEN_KEYW_ROTULO,
    TOKEN_KEYW_TIPO,
    TOKEN_KEYW_VARIAVEL,
    TOKEN_KEYW_PROCEDIMENTO,
    TOKEN_KEYW_FUNCAO,
    TOKEN_KEYW_INICIO,
    TOKEN_KEYW_FIM,
    TOKEN_KEYW_SE,
    TOKEN_KEYW_ENTAO,
    TOKEN_KEYW_SENAO,
    TOKEN_KEYW_FACA,
    TOKEN_KEYW_ENQUANTO,
    TOKEN_KEYW_VAPARA,
    
    TOKEN_SYMB_ATRIBUICAO,
    TOKEN_SYMB_MAIS,
    TOKEN_SYMB_MENOS,
    TOKEN_SYMB_VEZES,
    TOKEN_SYMB_DIVIDIR,
    TOKEN_SYMB_IGUAL,
    TOKEN_SYMB_DIFERENTE,
    TOKEN_SYMB_MENOR,
    TOKEN_SYMB_MENORIGUAL,
    TOKEN_SYMB_MAIOR,
    TOKEN_SYMB_MAIORIGUAL,
    TOKEN_SYMB_E,
    TOKEN_SYMB_OU,
    TOKEN_SYMB_NAO,
    TOKEN_SYMB_ABREPARENTESES,
    TOKEN_SYMB_FECHAPARENTESES,
    TOKEN_SYMB_ABRECOLCHETES,
    TOKEN_SYMB_FECHACOLCHETES,
    TOKEN_SYMB_VIRGULA,
    TOKEN_SYMB_PONTOVIRGULA,
    TOKEN_SYMB_DOISPONTOS,
    TOKEN_SYMB_PONTO,
    TOKEN_SYMB_ABRECOMENTARIO,
    TOKEN_SYMB_FECHACOMENTARIO,
    
    invalido,
    eof,
    
    null,
    identificador,
    numero,
};

typedef struct {
    string identificador;
} Token;

extern Token* 

#endif